name: Deploy front

on:
  push:
    branches:
      - staging
  workflow_dispatch:

env:
  NODE_VERSION: 24

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: npm ci

      - run: npm run typecheck

      - run: npm run lint

      - run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: dist/

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist/

      - name: Read parameter
        run: >
          DISTRIBUTION_ID=$(aws ssm get-parameter --name "/dev/front/cdn-id" --query "Parameter.Value" --output text)

          echo "DISTRIBUTION_ID=$DISTRIBUTION_ID" >> $GITHUB_ENV

      - run: aws s3 sync ./dist s3://app.front-dev-abdul.dev.br --delete
      - run: >
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/index.html"